-- Project Connect DROP File

DROP TABLE IF EXISTS Users CASCADE;

DROP TABLE IF EXISTS Organizations CASCADE;

DROP TABLE IF EXISTS Events CASCADE;

DROP TABLE IF EXISTS MapLocation CASCADE;

DROP TABLE IF EXISTS Posts CASCADE;

DROP TABLE IF EXISTS Comments CASCADE;

DROP TABLE IF EXISTS SupplyRequest CASCADE;

DROP TABLE IF EXISTS FulfillRequest CASCADE;

DROP TABLE IF EXISTS RSVP CASCADE;